### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by 2061574124** [sharkLoc/fqkit#8]
### i installed fqkit for many time because there are similar errors every time. Could you please help to see what the specific reason is and how to fix it
cargo install fakit
    Updating crates.io index
  Installing fakit v0.3.8
    Updating crates.io index
     Locking 191 packages to latest compatible versions
      Adding derive-new v0.5.9 (latest: v0.6.0)
      Adding env_logger v0.10.2 (latest: v0.11.3)
      Adding fixedbitset v0.4.2 (latest: v0.5.7)
      Adding heck v0.4.1 (latest: v0.5.0)
      Adding hermit-abi v0.1.19 (latest: v0.4.0)
      Adding hermit-abi v0.3.9 (latest: v0.4.0)
      Adding idna v0.5.0 (latest: v1.0.1)
      Adding itertools v0.11.0 (latest: v0.13.0)
      Adding linux-raw-sys v0.4.14 (latest: v0.6.4)
      Adding multimap v0.9.1 (latest: v0.10.0)
      Adding nalgebra v0.29.0 (latest: v0.33.0)
      Adding nalgebra-macros v0.1.0 (latest: v0.2.2)
      Adding noodles v0.75.0 (latest: v0.77.0)
      Adding noodles-bgzf v0.30.0 (latest: v0.31.0)
      Adding noodles-fasta v0.39.0 (latest: v0.40.0)
      Adding noodles-fastq v0.11.0 (latest: v0.12.0)
      Adding ordered-float v3.9.2 (latest: v4.2.0)
      Adding quick-error v1.2.3 (latest: v2.0.1)
      Adding rust-htslib v0.40.2 (latest: v0.47.0)
      Adding rustc_version v0.1.7 (latest: v0.4.0)
      Adding semver v0.1.20 (latest: v1.0.23)
      Adding simba v0.6.0 (latest: v0.9.0)
      Adding statrs v0.16.1 (latest: v0.17.1)
      Adding strum v0.25.0 (latest: v0.26.3)
      Adding strum_macros v0.25.3 (latest: v0.26.4)
      Adding syn v1.0.109 (latest: v2.0.68)
      Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.1+wasi-0.2.0)
      Adding windows-core v0.52.0 (latest: v0.57.0)
      Adding windows-sys v0.48.0 (latest: v0.52.0)
      Adding windows-targets v0.48.5 (latest: v0.52.5)
      Adding windows_aarch64_gnullvm v0.48.5 (latest: v0.52.5)
      Adding windows_aarch64_msvc v0.48.5 (latest: v0.52.5)
      Adding windows_i686_gnu v0.48.5 (latest: v0.52.5)
      Adding windows_i686_msvc v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_gnu v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_gnullvm v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_msvc v0.48.5 (latest: v0.52.5)
   Compiling libc v0.2.155
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling once_cell v1.19.0
   Compiling pkg-config v0.3.30
   Compiling autocfg v1.3.0
   Compiling libm v0.2.8
   Compiling cfg-if v1.0.0
   Compiling memchr v2.7.4
   Compiling vcpkg v0.2.15
   Compiling syn v1.0.109
   Compiling serde v1.0.203
   Compiling paste v1.0.15
   Compiling rustversion v1.0.17
   Compiling thiserror v1.0.61
   Compiling regex-syntax v0.8.4
   Compiling byteorder v1.5.0
   Compiling semver v0.1.20
   Compiling ppv-lite86 v0.2.17
   Compiling crossbeam-utils v0.8.20
   Compiling bytemuck v1.16.1
   Compiling typenum v1.17.0
   Compiling quick-error v1.2.3
   Compiling tinyvec_macros v0.1.1
   Compiling rustix v0.38.34
   Compiling lazy_static v1.5.0
   Compiling adler v1.0.2
   Compiling rawpointer v0.2.1
   Compiling utf8parse v0.2.2
   Compiling glob v0.3.1
   Compiling feature-probe v0.1.1
   Compiling linux-raw-sys v0.4.14
   Compiling heck v0.4.1
   Compiling bitflags v2.5.0
   Compiling hashbrown v0.14.5
   Compiling anstyle-query v1.1.0
   Compiling is_terminal_polyfill v1.70.0
   Compiling unicode-bidi v0.3.15
   Compiling colorchoice v1.0.1
   Compiling percent-encoding v2.3.1
   Compiling tinyvec v1.6.0
   Compiling crc32fast v1.4.2
   Compiling fs-utils v1.1.4
   Compiling equivalent v1.0.1
   Compiling anstyle v1.0.7
   Compiling anyhow v1.0.86
   Compiling miniz_oxide v0.7.4
   Compiling anstyle-parse v0.2.4
   Compiling bytes v1.6.0
   Compiling heck v0.5.0
   Compiling strsim v0.11.1
   Compiling itoa v1.0.11
   Compiling form_urlencoded v1.2.1
   Compiling bv v0.11.1
   Compiling rustc_version v0.1.7
   Compiling safe_arch v0.7.2
   Compiling ryu v1.0.18
   Compiling bit-vec v0.6.3
   Compiling either v1.12.0
   Compiling anstream v0.6.14
   Compiling clap_lex v0.7.1
   Compiling fixedbitset v0.4.2
   Compiling custom_derive v0.1.7
   Compiling fxhash v0.2.1
   Compiling iana-time-zone v0.1.60
   Compiling triple_accel v0.4.0
   Compiling humantime v2.1.0
   Compiling strum v0.25.0
   Compiling editdistancek v1.0.2
   Compiling num-traits v0.2.19
   Compiling matrixmultiply v0.3.8
   Compiling newtype_derive v0.1.6
   Compiling bytecount v0.6.8
   Compiling termcolor v1.4.1
   Compiling linear-map v1.2.0
   Compiling log v0.4.21
   Compiling bit-set v0.5.3
   Compiling ieee754 v0.2.6
   Compiling itertools v0.11.0
   Compiling colored v2.1.0
   Compiling aho-corasick v1.1.3
   Compiling flate2 v1.0.30
   Compiling bstr v1.9.1
   Compiling csv-core v0.1.11
   Compiling noodles-fastq v0.11.0
   Compiling wide v0.7.24
   Compiling quote v1.0.36
   Compiling crossbeam-channel v0.5.13
   Compiling indexmap v2.2.6
   Compiling syn v2.0.68
   Compiling getrandom v0.2.15
   Compiling is-terminal v0.4.12
   Compiling atty v0.2.14
   Compiling unicode-normalization v0.1.23
   Compiling noodles-core v0.15.0
   Compiling rand_core v0.6.4
   Compiling jobserver v0.1.31
   Compiling rand_chacha v0.3.1
   Compiling rand_pcg v0.3.1
   Compiling noodles-bgzf v0.30.0
   Compiling cc v1.0.100
   Compiling terminal_size v0.3.0
   Compiling clap_builder v4.5.7
   Compiling rand v0.8.5
   Compiling idna v0.5.0
   Compiling noodles-fasta v0.39.0
   Compiling petgraph v0.6.5
   Compiling num-complex v0.4.6
   Compiling num-integer v0.1.46
   Compiling approx v0.5.1
   Compiling itertools-num v0.1.3
   Compiling ordered-float v3.9.2
   Compiling chrono v0.4.38
   Compiling noodles v0.75.0
   Compiling url v2.5.2
   Compiling openssl-src v300.3.1+3.3.1
   Compiling cmake v0.1.50
   Compiling num-rational v0.4.2
   Compiling rand_distr v0.4.3
   Compiling ndarray v0.15.6
   Compiling regex-automata v0.4.7
   Compiling openssl-sys v0.9.102
   Compiling lzma-sys v0.1.20
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling curl-sys v0.4.72+curl-8.6.0
   Compiling hts-sys v2.1.4
   Compiling libz-sys v1.1.18
   Compiling simba v0.6.0
error: failed to run custom build command for `libz-sys v1.1.18`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install4eoQq7/release/build/libz-sys-8fccd39d1b50f2ab/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBZ_SYS_STATIC
  cargo:rerun-if-changed=build.rs
  cargo:rerun-if-changed=zng/cmake.rs
  cargo:rerun-if-changed=zng/cc.rs
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/tmp/cargo-install4eoQq7/release/build/libz-sys-ae01afca84789f11/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/home/dell/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libz-sys-1.1.18/src/zlib-ng" "-DBUILD_SHARED_LIBS=OFF" "-DZLIB_COMPAT=ON" "-DZLIB_ENABLE_TESTS=OFF" "-DWITH_GZFILEOP=ON" "-DCMAKE_INSTALL_PREFIX=/tmp/cargo-install4eoQq7/release/build/libz-sys-ae01afca84789f11/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"

  --- stderr
  thread 'main' panicked at /home/dell/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fakit v0.3.8`, intermediate artifacts can be found at `/tmp/cargo-install4eoQq7`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by sharkLoc** [comment]
do you see the err log:
> ailed to execute command: No such file or directory (os error 2)
is cmake not installed?

you can install cmake and try it againe

**Comment by 2061574124** [comment]
> do you see the err log:
> 
> > ailed to execute command: No such file or directory (os error 2)
> > is cmake not installed?
> 
> you can install cmake and try it againe

**After install cmake, and confirmed the version.**
dell@dell-PowerEdge-R720:~/bioinfo$ cmake --version
cmake version 3.16.3

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**but when i run: cargo install fqkit, and still gain error.**
dell@dell-PowerEdge-R720:~/bioinfo$ cargo install fqkit
    Updating crates.io index
  Installing fqkit v0.4.9
    Updating crates.io index
     Locking 237 packages to latest compatible versions
      Adding bitflags v1.3.2 (latest: v2.6.0)
      Adding clap v3.2.25 (latest: v4.5.7)
      Adding clap_lex v0.2.4 (latest: v0.7.1)
      Adding derive-new v0.5.9 (latest: v0.6.0)
      Adding env_logger v0.10.2 (latest: v0.11.3)
      Adding fixedbitset v0.4.2 (latest: v0.5.7)
      Adding freetype-sys v0.20.1 (latest: v0.21.0)
      Adding gif v0.12.0 (latest: v0.13.1)
      Adding hashbrown v0.12.3 (latest: v0.14.5)
      Adding heck v0.4.1 (latest: v0.5.0)
      Adding hermit-abi v0.1.19 (latest: v0.4.0)
      Adding hermit-abi v0.3.9 (latest: v0.4.0)
      Adding image v0.24.9 (latest: v0.25.1)
      Adding indexmap v1.9.3 (latest: v2.2.6)
      Adding itertools v0.11.0 (latest: v0.13.0)
      Adding linux-raw-sys v0.4.14 (latest: v0.6.4)
      Adding multimap v0.9.1 (latest: v0.10.0)
      Adding nalgebra v0.29.0 (latest: v0.33.0)
      Adding nalgebra-macros v0.1.0 (latest: v0.2.2)
      Adding ordered-float v3.9.2 (latest: v4.2.0)
      Adding os_str_bytes v6.6.1 (latest: v7.0.0)
      Adding rustc_version v0.1.7 (latest: v0.4.0)
      Adding semver v0.1.20 (latest: v1.0.23)
      Adding simba v0.6.0 (latest: v0.9.0)
      Adding statrs v0.16.1 (latest: v0.17.1)
      Adding strsim v0.10.0 (latest: v0.11.1)
      Adding strum v0.25.0 (latest: v0.26.3)
      Adding strum_macros v0.25.3 (latest: v0.26.4)
      Adding syn v1.0.109 (latest: v2.0.68)
      Adding ttf-parser v0.20.0 (latest: v0.21.1)
      Adding wasi v0.11.0+wasi-snapshot-preview1 (latest: v0.13.1+wasi-0.2.0)
      Adding windows-core v0.52.0 (latest: v0.57.0)
      Adding windows-sys v0.48.0 (latest: v0.52.0)
      Adding windows-targets v0.48.5 (latest: v0.52.5)
      Adding windows_aarch64_gnullvm v0.48.5 (latest: v0.52.5)
      Adding windows_aarch64_msvc v0.48.5 (latest: v0.52.5)
      Adding windows_i686_gnu v0.48.5 (latest: v0.52.5)
      Adding windows_i686_msvc v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_gnu v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_gnullvm v0.48.5 (latest: v0.52.5)
      Adding windows_x86_64_msvc v0.48.5 (latest: v0.52.5)
      Adding yansi v0.5.1 (latest: v1.0.1)
warning: spurious network error (3 tries remaining): [28] Timeout was reached (download of `cc v1.0.101` failed to transfer more than 10 bytes in 30s)
warning: spurious network error (3 tries remaining): [28] Timeout was reached (failed to download any data for `bitflags v2.6.0` within 30s)
  Downloaded either v1.13.0
  Downloaded bitflags v2.6.0
  Downloaded cc v1.0.101
  Downloaded 3 crates (144.0 KB) in 57.66s
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling libc v0.2.155
   Compiling autocfg v1.3.0
   Compiling cfg-if v1.0.0
   Compiling libm v0.2.8
   Compiling pkg-config v0.3.30
   Compiling cc v1.0.101
   Compiling bytemuck v1.16.1
   Compiling semver v1.0.23
   Compiling memchr v2.7.4
   Compiling syn v1.0.109
   Compiling lazy_static v1.5.0
   Compiling simd-adler32 v0.3.7
   Compiling ident_case v1.0.1
   Compiling crossbeam-utils v0.8.20
   Compiling serde v1.0.203
   Compiling strsim v0.11.1
   Compiling log v0.4.21
   Compiling bitflags v2.6.0
   Compiling fnv v1.0.7
   Compiling adler v1.0.2
   Compiling paste v1.0.15
   Compiling ppv-lite86 v0.2.17
   Compiling bitflags v1.3.2
   Compiling rustix v0.38.34
   Compiling regex-syntax v0.8.4
   Compiling byteorder v1.5.0
   Compiling rustversion v1.0.17
   Compiling semver v0.1.20
   Compiling typenum v1.17.0
   Compiling thiserror v1.0.61
   Compiling rawpointer v0.2.1
   Compiling utf8parse v0.2.2
   Compiling itoa v1.0.11
   Compiling linux-raw-sys v0.4.14
   Compiling once_cell v1.19.0
   Compiling powerfmt v0.2.0
   Compiling time-core v0.1.2
   Compiling termcolor v1.4.1
   Compiling crc32fast v1.4.2
   Compiling rustc_version v0.1.7
   Compiling anstyle-parse v0.2.4
   Compiling libloading v0.8.4
   Compiling color_quant v1.1.0
   Compiling colorchoice v1.0.1
   Compiling anstyle-query v1.1.0
   Compiling miniz_oxide v0.7.4
   Compiling safe_arch v0.7.2
   Compiling aho-corasick v1.1.3
   Compiling flate2 v1.0.30
   Compiling wide v0.7.24
   Compiling fdeflate v0.3.4
   Compiling feature-probe v0.1.1
   Compiling num-traits v0.2.19
   Compiling matrixmultiply v0.3.8
   Compiling yeslogic-fontconfig-sys v5.0.0
   Compiling indexmap v1.9.3
   Compiling num-conv v0.1.0
   Compiling is_terminal_polyfill v1.70.0
   Compiling anstyle v1.0.7
   Compiling bv v0.11.1
   Compiling dlib v0.5.2
   Compiling deranged v0.3.11
   Compiling num_threads v0.1.7
   Compiling newtype_derive v0.1.6
   Compiling font-kit v0.13.2
   Compiling freetype-sys v0.20.1
   Compiling lzma-sys v0.1.20
   Compiling bzip2-sys v0.1.11+1.0.8
   Compiling anstream v0.6.14
   Compiling hashbrown v0.14.5
   Compiling hashbrown v0.12.3
   Compiling iana-time-zone v0.1.60
   Compiling equivalent v1.0.1
   Compiling heck v0.4.1
   Compiling time-macros v0.2.18
   Compiling os_str_bytes v6.6.1
   Compiling clap_lex v0.7.1
   Compiling same-file v1.0.6
   Compiling jpeg-decoder v0.3.1
   Compiling plotters-backend v0.3.6
   Compiling heck v0.5.0
   Compiling weezl v0.1.8
   Compiling anyhow v1.0.86
   Compiling gif v0.12.0
   Compiling clap_lex v0.2.4
   Compiling walkdir v2.5.0
   Compiling png v0.17.13
   Compiling csv-core v0.1.11
   Compiling colored v2.1.0
   Compiling either v1.13.0
   Compiling textwrap v0.16.1
   Compiling bit-vec v0.6.3
   Compiling indexmap v2.2.6
   Compiling strsim v0.10.0
   Compiling ryu v1.0.18
   Compiling fixedbitset v0.4.2
   Compiling humantime v2.1.0
   Compiling float-ord v0.3.2
   Compiling itertools v0.11.0
   Compiling bit-set v0.5.3
   Compiling plotters-svg v0.3.6
   Compiling rgb v0.8.37
   Compiling fxhash v0.2.1
   Compiling strum v0.25.0
   Compiling ttf-parser v0.20.0
   Compiling triple_accel v0.4.0
   Compiling bytecount v0.6.8
   Compiling editdistancek v1.0.2
   Compiling yansi v0.5.1
   Compiling custom_derive v0.1.7
   Compiling drawille v0.3.0
   Compiling textplots v0.8.6
   Compiling petgraph v0.6.5
   Compiling regex-automata v0.4.7
   Compiling regex v1.10.5
error: failed to run custom build command for `yeslogic-fontconfig-sys v5.0.0`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installcEMFf7/release/build/yeslogic-fontconfig-sys-70d0edb7e4050a10/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=RUST_FONTCONFIG_DLOPEN
  cargo:rerun-if-env-changed=FONTCONFIG_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=FONTCONFIG_STATIC
  cargo:rerun-if-env-changed=FONTCONFIG_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at /home/dell/.cargo/registry/src/index.crates.io-6f17d22bba15001f/yeslogic-fontconfig-sys-5.0.0/build.rs:8:48:
  called `Result::unwrap()` on an `Err` value: "\npkg-config exited with status code 1\n> PKG_CONFIG_ALLOW_SYSTEM_LIBS=1 PKG_CONFIG_ALLOW_SYSTEM_CFLAGS=1 pkg-config --libs --cflags fontconfig\n\nThe system library `fontconfig` required by crate `yeslogic-fontconfig-sys` was not found.\nThe file `fontconfig.pc` needs to be installed and the PKG_CONFIG_PATH environment variable must contain its parent directory.\nThe PKG_CONFIG_PATH environment variable is not set.\n\nHINT: if you have installed the library, try setting PKG_CONFIG_PATH to the directory containing `fontconfig.pc`.\n"
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `fqkit v0.4.9`, intermediate artifacts can be found at `/tmp/cargo-installcEMFf7`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by sharkLoc** [comment]
your system need some dependence,
download file from here: https://github.com/sharkLoc/fqkit/releases/download/version0.4.9/fqkit
